version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - .:/todo_ver2
      - todo_ver2_bundle:/usr/local/bundle:cached
      - todo_ver2_vender:/todo_ver2/vendor
      - todo_ver2_temp:/todo_ver2/tmp
      - todo_ver2_log:/todo_ver2/log
      - todo_ver2_git:/todo_ver2/.git
      - todo_ver2_node_module:/todo_ver2/frontend/node_modules
    stdin_open: true
    tty: true
    command: /bin/sh -c "bundle install; rm -f /todo_ver2/tmp/pids/server.pid; rails s -b 0.0.0.0 -p 3000"
    depends_on:
      - db
  db:
    image: postgres:10.1
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
    ports:
      - 5432:5432
    volumes:
      - todo_ver2_db_data:/var/lib/postgresql/data
volumes:
  todo_ver2_bundle:
  todo_ver2_vender:
  todo_ver2_temp:
  todo_ver2_log:
  todo_ver2_git:
  todo_ver2_node_module:
  todo_ver2_db_data:
